// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM0IFIpLcfrCE6HoHaKAin2DZnJhAET30',
    appId: '1:3336360452:web:91a13983dcc2158ade1b51',
    messagingSenderId: '3336360452',
    projectId: 'lodge-booking-flutter',
    authDomain: 'lodge-booking-flutter.firebaseapp.com',
    storageBucket: 'lodge-booking-flutter.firebasestorage.app',
    measurementId: 'G-22NTMK8M5R',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM0IFIpLcfrCE6HoHaKAin2DZnJhAET30',
    appId: '1:3336360452:web:1ac03822b04d2874de1b51',
    messagingSenderId: '3336360452',
    projectId: 'lodge-booking-flutter',
    authDomain: 'lodge-booking-flutter.firebaseapp.com',
    storageBucket: 'lodge-booking-flutter.firebasestorage.app',
    measurementId: 'G-2VW9PLHYEW',
  );
}
