// GENERATED BY FLUTTERFIRE CLI. Replace by running: flutterfire configure
// Placeholder FirebaseOptions — run `flutterfire configure` to populate real values.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        return const FirebaseOptions(
          apiKey: 'WEB_API_KEY',
          appId: 'WEB_APP_ID',
          messagingSenderId: 'SENDER_ID',
          projectId: 'YOUR_PROJECT_ID',
          authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
          storageBucket: 'YOUR_PROJECT_ID.appspot.com',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
