// GENERATED BY FLUTTERFIRE CLI. Replace by running: flutterfire configure
// Placeholder FirebaseOptions — run `flutterfire configure` to populate real values.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        return const FirebaseOptions(
          apiKey: 'AIzaSyAgvkYCrWIvgOWYh6SP0dAzEYw515iTZ5o',
          appId: '1:3336360452:web:YOUR_WEB_APP_ID',
          messagingSenderId: '3336360452',
          projectId: 'lodge-booking-flutter',
          authDomain: 'lodge-booking-flutter.firebaseapp.com',
          storageBucket: 'lodge-booking-flutter.firebasestorage.app',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
