// GENERATED BY FLUTTERFIRE CLI. Replace by running: flutterfire configure
// Placeholder FirebaseOptions — run `flutterfire configure` to populate real values.
// Supports Android + Web for the client app.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgvkYCrWIvgOWYh6SP0dAzEYw515iTZ5o',
    appId: '1:3336360452:web:YOUR_WEB_APP_ID',
    messagingSenderId: '3336360452',
    projectId: 'lodge-booking-flutter',
    authDomain: 'lodge-booking-flutter.firebaseapp.com',
    storageBucket: 'lodge-booking-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgvkYCrWIvgOWYh6SP0dAzEYw515iTZ5o',
    appId: '1:3336360452:android:e69e34c84b477324de1b51',
    messagingSenderId: '3336360452',
    projectId: 'lodge-booking-flutter',
    storageBucket: 'lodge-booking-flutter.firebasestorage.app',
  );
}
