// GENERATED BY FLUTTERFIRE CLI. Replace by running: flutterfire configure
// Placeholder FirebaseOptions — run `flutterfire configure` to populate real values.
// Supports Android + Web for the client app.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALlgxNLbMbgRH_QcpisB4rDIUTfhBwrLk',
    appId: '1:145812182201:web:c38fa970770e1c7da3f768',
    messagingSenderId: '145812182201',
    projectId: 'hotel-booking-app-7aada',
    authDomain: 'hotel-booking-app-7aada.firebaseapp.com',
    databaseURL: 'https://hotel-booking-app-7aada-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hotel-booking-app-7aada.firebasestorage.app',
    measurementId: 'G-DLVDHHQ8KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8GZqBndb3539ajYFAc2Qpk_LWZUTtNhY',
    appId: '1:145812182201:android:8c24303481f18502a3f768',
    messagingSenderId: '145812182201',
    projectId: 'hotel-booking-app-7aada',
    databaseURL: 'https://hotel-booking-app-7aada-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hotel-booking-app-7aada.firebasestorage.app',
  );
}
